### ISSUE TITLE
交易管家的接口问题

### ISSUE THREAD

**Issue by darwintree** [ahKevinXy/go-cmb#6]
目前交易管家相关有两套API https://openbiz.cmbchina.com/developer/UI/Business/CloudDirectConnect/Public/DocumentCenter/DocDetail.aspx?bizkey=DCCT20201215090812098&fabizkey=1&treeID=100055722

根据文档页相关说明，
1. 凡对接“新增记账子单元-NTDMAADD”接口，须同步对接“查询记账子单元信息-NTDMALST”、“关闭记账子单元-NTDMADLT”（https://openbiz.cmbchina.com/developer/UI/Business/CloudDirectConnect/Public/DocumentCenter/DocDetail.aspx?bizkey=DCCT20201215090812098&fabizkey=1&treeID=100055722）
2. 凡对接“新增记账子单元-NTDUMADD”接口，须同步对接“关闭记账子单元-NTDUMDLT”（https://openbiz.cmbchina.com/developer/UI/Business/CloudDirectConnect/Public/DocumentCenter/DocDetail.aspx?bizkey=DCCT20201215090812098&fabizkey=1&treeID=100055749）

目前的接口混用了这两类接口，可能切换至同一类更好。（我个人倾向于使用前者，返回值更友好）

```go
// 管家 管理
const (
	CmbUnitManageAddAccount                 = "NTDMAADD"    //新增记账子单元 NTDMAADD
	CmbUnitManageCloseAccount               = "NTDUMDLT"    //关闭记账子单元NTDUMDLT
        ......
)
```

**Comment by ahKevinXy** [comment]
好像是的，我之前对接有点混了，我打算用v1 v2来区分一下
